export const achievementFamilies = [
    {
        key: "workouts",
        slug: "rhythm",
        title: "Ритм",
        title_i18n_key: "achievements.workouts.title",
        sort_order: 1,
    },
    {
        key: "streak",
        slug: "no-breaks",
        title: "Без пауз",
        title_i18n_key: "achievements.streak.title",
        sort_order: 2,
    },
    {
        key: "volume",
        slug: "tonnage",
        title: "Тонаж",
        title_i18n_key: "achievements.volume.title",
        sort_order: 3,
    },
    {
        key: "sets",
        slug: "sets",
        title: "Серії",
        title_i18n_key: "achievements.sets.title",
        sort_order: 4,
    },
    {
        key: "exercises",
        slug: "arsenal",
        title: "Арсенал",
        title_i18n_key: "achievements.exercises.title",
        sort_order: 5,
    },
    {
        key: "1rm",
        slug: "peak-strength",
        title: "Пік сили",
        title_i18n_key: "achievements.1rm.title",
        sort_order: 6,
    },
    {
        key: "reps",
        slug: "reps",
        title: "Повтори",
        title_i18n_key: "achievements.reps.title",
        sort_order: 7,
    },
    {
        key: "duration",
        slug: "gym-hours",
        title: "Години в залі",
        title_i18n_key: "achievements.duration.title",
        sort_order: 8,
    },
    {
        key: "balance",
        slug: "balance",
        title: "Баланс",
        title_i18n_key: "achievements.balance.title",
        sort_order: 9,
    },
];

export const achievementDefinitions = [
    {
        id: "workouts_bronze",
        family_key: "workouts",
        metric_key: "workouts",
        description_template: "Завершіть {target} тренувань",
        description_i18n_key: "achievements.workouts.description.bronze",
        tier: "bronze",
        target: 15,
        tier_order: 1,
    },
    {
        id: "workouts_silver",
        family_key: "workouts",
        metric_key: "workouts",
        description_template: "Завершіть {target} тренувань",
        description_i18n_key: "achievements.workouts.description.silver",
        tier: "silver",
        target: 40,
        tier_order: 2,
    },
    {
        id: "workouts_gold",
        family_key: "workouts",
        metric_key: "workouts",
        description_template: "Завершіть {target} тренувань",
        description_i18n_key: "achievements.workouts.description.gold",
        tier: "gold",
        target: 140,
        tier_order: 3,
    },
    {
        id: "streak_bronze",
        family_key: "streak",
        metric_key: "streak",
        description_template: "Тримайте ритм {target} тижнів поспіль",
        description_i18n_key: "achievements.streak.description.bronze",
        tier: "bronze",
        target: 5,
        tier_order: 1,
    },
    {
        id: "streak_silver",
        family_key: "streak",
        metric_key: "streak",
        description_template: "Тримайте ритм {target} тижнів поспіль",
        description_i18n_key: "achievements.streak.description.silver",
        tier: "silver",
        target: 10,
        tier_order: 2,
    },
    {
        id: "streak_gold",
        family_key: "streak",
        metric_key: "streak",
        description_template: "Тримайте ритм {target} тижнів поспіль",
        description_i18n_key: "achievements.streak.description.gold",
        tier: "gold",
        target: 20,
        tier_order: 3,
    },
    {
        id: "volume_bronze",
        family_key: "volume",
        metric_key: "volume",
        description_template: "Накопичте {target} кг загального тоннажу",
        description_i18n_key: "achievements.volume.description.bronze",
        tier: "bronze",
        target: 20000,
        tier_order: 1,
    },
    {
        id: "volume_silver",
        family_key: "volume",
        metric_key: "volume",
        description_template: "Накопичте {target} кг загального тоннажу",
        description_i18n_key: "achievements.volume.description.silver",
        tier: "silver",
        target: 50000,
        tier_order: 2,
    },
    {
        id: "volume_gold",
        family_key: "volume",
        metric_key: "volume",
        description_template: "Накопичте {target} кг загального тоннажу",
        description_i18n_key: "achievements.volume.description.gold",
        tier: "gold",
        target: 180000,
        tier_order: 3,
    },
    {
        id: "sets_bronze",
        family_key: "sets",
        metric_key: "sets",
        description_template: "Закрийте {target} підходів",
        description_i18n_key: "achievements.sets.description.bronze",
        tier: "bronze",
        target: 125,
        tier_order: 1,
    },
    {
        id: "sets_silver",
        family_key: "sets",
        metric_key: "sets",
        description_template: "Закрийте {target} підходів",
        description_i18n_key: "achievements.sets.description.silver",
        tier: "silver",
        target: 320,
        tier_order: 2,
    },
    {
        id: "sets_gold",
        family_key: "sets",
        metric_key: "sets",
        description_template: "Закрийте {target} підходів",
        description_i18n_key: "achievements.sets.description.gold",
        tier: "gold",
        target: 1200,
        tier_order: 3,
    },
    {
        id: "exercises_bronze",
        family_key: "exercises",
        metric_key: "exercises",
        description_template: "Освойте {target} різних вправ",
        description_i18n_key: "achievements.exercises.description.bronze",
        tier: "bronze",
        target: 15,
        tier_order: 1,
    },
    {
        id: "exercises_silver",
        family_key: "exercises",
        metric_key: "exercises",
        description_template: "Освойте {target} різних вправ",
        description_i18n_key: "achievements.exercises.description.silver",
        tier: "silver",
        target: 28,
        tier_order: 2,
    },
    {
        id: "exercises_gold",
        family_key: "exercises",
        metric_key: "exercises",
        description_template: "Освойте {target} різних вправ",
        description_i18n_key: "achievements.exercises.description.gold",
        tier: "gold",
        target: 45,
        tier_order: 3,
    },
    {
        id: "1rm_bronze",
        family_key: "1rm",
        metric_key: "1rm",
        description_template: "Досягніть 1RM у {target} кг в будь-якій вправі",
        description_i18n_key: "achievements.1rm.description.bronze",
        tier: "bronze",
        target: 100,
        tier_order: 1,
    },
    {
        id: "1rm_silver",
        family_key: "1rm",
        metric_key: "1rm",
        description_template: "Досягніть 1RM у {target} кг в будь-якій вправі",
        description_i18n_key: "achievements.1rm.description.silver",
        tier: "silver",
        target: 130,
        tier_order: 2,
    },
    {
        id: "1rm_gold",
        family_key: "1rm",
        metric_key: "1rm",
        description_template: "Досягніть 1RM у {target} кг в будь-якій вправі",
        description_i18n_key: "achievements.1rm.description.gold",
        tier: "gold",
        target: 180,
        tier_order: 3,
    },
    {
        id: "reps_bronze",
        family_key: "reps",
        metric_key: "reps",
        description_template: "Зробіть {target} повторень загалом",
        description_i18n_key: "achievements.reps.description.bronze",
        tier: "bronze",
        target: 1500,
        tier_order: 1,
    },
    {
        id: "reps_silver",
        family_key: "reps",
        metric_key: "reps",
        description_template: "Зробіть {target} повторень загалом",
        description_i18n_key: "achievements.reps.description.silver",
        tier: "silver",
        target: 4500,
        tier_order: 2,
    },
    {
        id: "reps_gold",
        family_key: "reps",
        metric_key: "reps",
        description_template: "Зробіть {target} повторень загалом",
        description_i18n_key: "achievements.reps.description.gold",
        tier: "gold",
        target: 16000,
        tier_order: 3,
    },
    {
        id: "duration_bronze",
        family_key: "duration",
        metric_key: "duration",
        description_template: "Проведіть {target} годин у тренуваннях",
        description_i18n_key: "achievements.duration.description.bronze",
        tier: "bronze",
        target: 12,
        tier_order: 1,
    },
    {
        id: "duration_silver",
        family_key: "duration",
        metric_key: "duration",
        description_template: "Проведіть {target} годин у тренуваннях",
        description_i18n_key: "achievements.duration.description.silver",
        tier: "silver",
        target: 32,
        tier_order: 2,
    },
    {
        id: "duration_gold",
        family_key: "duration",
        metric_key: "duration",
        description_template: "Проведіть {target} годин у тренуваннях",
        description_i18n_key: "achievements.duration.description.gold",
        tier: "gold",
        target: 110,
        tier_order: 3,
    },
    {
        id: "balance_bronze",
        family_key: "balance",
        metric_key: "balance",
        description_template: "Охопіть {target} груп м'язів у своєму арсеналі",
        description_i18n_key: "achievements.balance.description.bronze",
        tier: "bronze",
        target: 4,
        tier_order: 1,
    },
    {
        id: "balance_silver",
        family_key: "balance",
        metric_key: "balance",
        description_template: "Охопіть {target} груп м'язів у своєму арсеналі",
        description_i18n_key: "achievements.balance.description.silver",
        tier: "silver",
        target: 5,
        tier_order: 2,
    },
    {
        id: "balance_gold",
        family_key: "balance",
        metric_key: "balance",
        description_template: "Охопіть {target} груп м'язів у своєму арсеналі",
        description_i18n_key: "achievements.balance.description.gold",
        tier: "gold",
        target: 6,
        tier_order: 3,
    },
];